package grammar.parsetree.node;

public enum NodeType
{
	TYPE, ID, VAR,
	METHOD_DECL, FIELD_DECL, FIELD, METHOD_ARG,
	STATEMENT,
	LOCATION, METHOD_CALL, CALL_OUT,
	BLOCK, IF, ASSIGN, BREAK, CONTINUE, FOR, RETURN,
	CHAR_LIT, STRING_LIT, INT_LIT, BOOLEAN_LIT,
	OTHER;
}
